version: "3.9"

services:

  webhook-sql:
    image: library/mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: trello-webhook
#    volumes:
#      - webhook-sql:/var/lib/mysql
    ports:
      - 3307:3306

#networks:
#  mysql-db:
#    driver: bridge
#volumes:
#  webhook-sql: